const promise = new Promise(function (resolve, reject) {
    reject("oops");
});

promise.catch(function (error) {
    console.error("ERROR", error);
});
